repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        pass_filenames: true
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort --profile black
        pass_filenames: true
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        pass_filenames: true
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy --install-types --non-interactive sxm_tmk
        pass_filenames: false
        language: system
        types: [python]
